DROP DATABASE IF EXISTS bdLugares;
CREATE DATABASE bdLugares;
USE bdLugares;

CREATE TABLE IF NOT EXISTS lugares (
idLugar		INT NOT NULL AUTO_INCREMENT,
imagen      MEDIUMBLOB NOT NULL,
nombre		VARCHAR(30) NOT NULL,
descripcion	VARCHAR(100) NOT NULL,
horario		VARCHAR(30) NOT NULL,
ubicación	VARCHAR(50) NOT NULL,
enlaceWeb   VARCHAR(100) DEFAULT NULL,
etiqueta	VARCHAR(30) NOT NULL,

PRIMARY KEY (idLugar)) DEFAULT CHARACTER SET utf8;
