// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_du5jFdX9TlYIQV7iU3Btv2Xe2az47j0',
    appId: '1:626039672376:web:64d7b28237387fe2d720cd',
    messagingSenderId: '626039672376',
    projectId: 'programacion-movil-87ace',
    authDomain: 'programacion-movil-87ace.firebaseapp.com',
    storageBucket: 'programacion-movil-87ace.firebasestorage.app',
    measurementId: 'G-ZL58NTQ931',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH9VyN-Ba_6jcJu5y1FioJ_XOOlQzxn48',
    appId: '1:626039672376:android:c7ac3cd46c8dc844d720cd',
    messagingSenderId: '626039672376',
    projectId: 'programacion-movil-87ace',
    storageBucket: 'programacion-movil-87ace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVC1TjyrpOgXDU9rRGWLd_p52vCkkFqbA',
    appId: '1:626039672376:ios:a88a0e3a7bea0a7ad720cd',
    messagingSenderId: '626039672376',
    projectId: 'programacion-movil-87ace',
    storageBucket: 'programacion-movil-87ace.firebasestorage.app',
    iosBundleId: 'com.unam.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVC1TjyrpOgXDU9rRGWLd_p52vCkkFqbA',
    appId: '1:626039672376:ios:a88a0e3a7bea0a7ad720cd',
    messagingSenderId: '626039672376',
    projectId: 'programacion-movil-87ace',
    storageBucket: 'programacion-movil-87ace.firebasestorage.app',
    iosBundleId: 'com.unam.proyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_du5jFdX9TlYIQV7iU3Btv2Xe2az47j0',
    appId: '1:626039672376:web:b3a3624069f2865ed720cd',
    messagingSenderId: '626039672376',
    projectId: 'programacion-movil-87ace',
    authDomain: 'programacion-movil-87ace.firebaseapp.com',
    storageBucket: 'programacion-movil-87ace.firebasestorage.app',
    measurementId: 'G-DGV903JXCR',
  );
}
